name: Original Validator

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  dispatch-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.3
          arch: 'x64'
      - name: Run Validator
        run: julia ./validation/validator.jl