name: Unit test

on:
  create:
    tags:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '20 00 1 * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.3', '1', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest, macos-11]
    env:
      PYTHON: ""
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: "Unit Test"
        uses: julia-actions/julia-runtest@master

      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
